THE DEVOPS GROUP CAN FINALLY BOAST OF GIT, JENKINS, DOCKER AND ANSIBLE. Yes we did......yeh!!!!!

THIS WAS DONE USING TWO PLAYBOOKS AUTOMATION.
THIS IS THE THIRD TRIAL FOR THIS AUTOMATION....HOOOOOHHH!

